using Entities.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KaloriTakipUygulamasi_DAL.Configurations
{
    public class Food_CFG : IEntityTypeConfiguration<Food>
    {
        public void Configure(EntityTypeBuilder<Food> builder)
        {
            builder.ToTable("Foods");
            builder.HasKey(x => x.FoodID);
            builder.HasOne(x => x.FoodCategory).WithMany(x => x.Foods).HasForeignKey(x => x.FoodCategoryID);
            builder.Property(x=>x.FoodName).IsRequired().HasMaxLength(50).HasColumnType("nvarchar").HasColumnName("Food Name");
            builder.Property(x=>x.Description).IsRequired().HasMaxLength(1000).HasColumnType("nvarchar");
            builder.Property(x => x.FoodPicture).HasColumnType("nvarchar").HasMaxLength(500).HasColumnName("Food Picture");
            builder.Property(x => x.FoodCategoryID).HasColumnName("Food Category ID");
            builder.HasData(
            new Food { FoodID = 1, FoodName = "Ground Baby Beef (Half Fat)", FoodCategoryID = 1, Protein = 21, Carbonhydrate = 0, Fat = 3.6, Calorie = 120, Description = "Beef, in general, refers to the meat of young cattle or calves. Beef is obtained from the muscle tissue of cows or calves and is commonly known for being nutritious, flavorful, and versatile in cooking. It contains high amounts of protein, iron, zinc, and B vitamins. Beef can be consumed by grilling, used in meat dishes, making meatballs, or incorporated into various recipes. It is a popular choice among red meats and is widely consumed in various cultures.", FoodPicture = "../../../images/foodimages/danakıyma.jfif", Amount = 100 },
            new Food { FoodID = 2, FoodName = "Ground Baby Beef (Fatty)", FoodCategoryID = 1, Protein = 20, Carbonhydrate = 0, Fat = 8.2, Calorie = 170, Description = "Beef, in general, refers to the meat of young cattle or calves. Beef is obtained from the muscle tissue of cows or calves and is commonly known for being nutritious, flavorful, and versatile in cooking. It contains high amounts of protein, iron, zinc, and B vitamins. Beef can be consumed by grilling, used in meat dishes, making meatballs, or incorporated into various recipes. It is a popular choice among red meats and is widely consumed in various cultures.", FoodPicture = "../../../images/foodimages/danakıyma.jfif", Amount = 100 },
            new Food { FoodID = 3, FoodName = "Calf Thigh", FoodCategoryID = 1, Protein = 20, Carbonhydrate = 0, Fat = 1, Calorie = 103, Description = "Beef, in general, refers to the meat of young cattle or calves. Beef is obtained from the muscle tissue of cows or calves and is commonly known for being nutritious, flavorful, and versatile in cooking. It contains high amounts of protein, iron, zinc, and B vitamins. Beef can be consumed by grilling, used in meat dishes, making meatballs, or incorporated into various recipes. It is a popular choice among red meats and is widely consumed in various cultures.", FoodPicture = "../../../images/foodimages/danabut.jfif", Amount = 100 },
            new Food { FoodID = 4, FoodName = "Ground Mutton (Fatless)", FoodCategoryID = 1, Protein = 19, Carbonhydrate = 0, Fat = 13, Calorie = 200, Description = "Sheep meat, also known as mutton, is a meat product obtained from sheep. It is considered a nutritious source due to its high protein, vitamin, and mineral content. It is cooked and consumed in various ways across different cultures, playing a significant role in local cuisines. However, health factors, cooking methods, and individual dietary preferences should be taken into consideration.", FoodPicture = "../../../images/foodimages/KoyunKıyma.jfif", Amount = 100 },
            new Food { FoodID = 5, FoodName = "Ground Mutton (Half Fat)", FoodCategoryID = 1, Protein = 18, Carbonhydrate = 0, Fat = 16, Calorie = 223, Description = "Sheep meat, also known as mutton, is a meat product obtained from sheep. It is considered a nutritious source due to its high protein, vitamin, and mineral content. It is cooked and consumed in various ways across different cultures, playing a significant role in local cuisines. However, health factors, cooking methods, and individual dietary preferences should be taken into consideration.", FoodPicture = "../../../images/foodimages/KoyunKıyma.jfif", Amount = 100 },
            new Food { FoodID = 6, FoodName = "Ground Mutton (Fatty)", FoodCategoryID = 1, Protein = 18, Carbonhydrate = 0, Fat = 38, Calorie = 430, Description = "Sheep meat, also known as mutton, is a meat product obtained from sheep. It is considered a nutritious source due to its high protein, vitamin, and mineral content. It is cooked and consumed in various ways across different cultures, playing a significant role in local cuisines. However, health factors, cooking methods, and individual dietary preferences should be taken into consideration.", FoodPicture = "../../../images/foodimages/KoyunKıyma.jfif", Amount = 100 },
            new Food { FoodID = 7, FoodName = "Sheep Thigh", FoodCategoryID = 1, Protein = 18, Carbonhydrate = 0, Fat = 18, Calorie = 250, Description = "Sheep meat, also known as mutton, is a meat product obtained from sheep. It is considered a nutritious source due to its high protein, vitamin, and mineral content. It is cooked and consumed in various ways across different cultures, playing a significant role in local cuisines. However, health factors, cooking methods, and individual dietary preferences should be taken into consideration.", FoodPicture = "../../../images/foodimages/koyunbut.jfif", Amount = 100 },
            new Food { FoodID = 8, FoodName = "Ground Beef(cattle) (Half Fat)", FoodCategoryID = 1, Protein = 21, Carbonhydrate = 0, Fat = 21, Calorie = 283, Description = "Beef is a meat product obtained from cattle. It is known as a nutritious source due to its high protein content and is used in various dishes.", FoodPicture = "../../../images/foodimages/sıgırkıyma.jfif", Amount = 100 },
            new Food { FoodID = 9, FoodName = "Ground Beef (cattle) (Fatty)", FoodCategoryID = 1, Protein = 17, Carbonhydrate = 0, Fat = 29, Calorie = 345, Description = "Beef is a meat product obtained from cattle. It is known as a nutritious source due to its high protein content and is used in various dishes.", FoodPicture = "../../../images/foodimages/sıgırkıyma.jfif", Amount = 100 },
            new Food { FoodID = 10, FoodName = "Edgebone", FoodCategoryID = 1, Protein = 19, Carbonhydrate = 0, Fat = 13, Calorie = 200, Description = "Beef is a meat product obtained from cattle. It is known as a nutritious source due to its high protein content and is used in various dishes.", FoodPicture = "../../../images/foodimages/sıgırbutu.jfif", Amount = 100 },

            new Food { FoodID = 11, FoodName = "Turkey", FoodCategoryID = 2, Protein = 20, Carbonhydrate = 4, Fat = 8, Calorie = 160, Description = "Turkey meat is a meat product obtained from turkeys. It is known for its low fat content and is a flavorful source of protein.", FoodPicture = "../../../images/foodimages/hindi.jfif", Amount = 100 },
            new Food { FoodID = 12, FoodName = "Chicken Drumstick", FoodCategoryID = 2, Protein = 21, Carbonhydrate = 0, Fat = 3, Calorie = 122, Description = "Chicken thigh is a rich source of protein, vitamins, and minerals. It is considered a good protein source, providing essential amino acids for the body. It also contains important minerals like iron, zinc, B vitamins, and phosphorus. However, the exact nutritional values may vary depending on factors such as cooking method, size, and other variables.", FoodPicture = "../../../images/foodimages/tavukbut.jfif", Amount = 100 },
            new Food { FoodID = 13, FoodName = "Chicken Livers", FoodCategoryID = 2, Protein = 22, Carbonhydrate = 1, Fat = 5, Calorie = 147, Description = "Chicken liver is a nutrient-rich food source, high in protein, iron, B vitamins, and vitamin A.", FoodPicture = "../../../images/foodimages/tavulciger.jfif", Amount = 100 },
            new Food { FoodID = 14, FoodName = "Chicken Breast", FoodCategoryID = 2, Protein = 23, Carbonhydrate = 0, Fat = 1, Calorie = 104, Description = "Chicken breast is a food source that is high in protein and B vitamins, while being low in fat.", FoodPicture = "../../../images/foodimages/tavulgögus.jfif", Amount = 100 },

            new Food { FoodID = 15, FoodName = "Dried Broad Beans", FoodCategoryID = 3, Protein = 25, Carbonhydrate = 53.7, Fat = 1.7, Calorie = 354, Description = "Dried broad beans are a plant-based source of protein and fiber. They also contain carbohydrates, vitamins, and minerals.", FoodPicture = "../../../images/foodimages/kurubakla.jfif", Amount = 100 },
            new Food { FoodID = 16, FoodName = "Broad Beans", FoodCategoryID = 3, Protein = 5.7, Carbonhydrate = 9.8, Fat = 0.4, Calorie = 72, Description = "Broad beans are a nutritious vegetable, rich in protein, fiber, vitamins, and minerals. They strengthen the immune system, support digestion, and provide energy.", FoodPicture = "../../../images/foodimages/tazebakla.jfif", Amount = 100 },
            new Food { FoodID = 17, FoodName = "Okra", FoodCategoryID = 3, Protein = 6, Carbonhydrate = 4, Fat = 0.1, Calorie = 42, Description = "Fresh okra is a low-calorie vegetable that is rich in fiber, vitamins, and minerals. Its high fiber content supports digestive health and provides a feeling of fullness. It also contains important nutrients such as vitamin C, vitamin K, iron, and folate. Fresh okra strengthens the immune system, promotes blood health, and can be preferred as part of a healthy diet.", FoodPicture = "../../../images/foodimages/bamya.jfif", Amount = 100 },
            new Food { FoodID = 18, FoodName = "Dried Kidney Beans", FoodCategoryID = 3, Protein = 21, Carbonhydrate = 57, Fat = 1.5, Calorie = 346, Description = "Dried kidney beans are a nutritious legume that is high in protein, fiber, vitamins, and minerals. Protein supports muscle development and repair, while fiber aids in digestion and provides a feeling of fullness. It also contains important nutrients such as iron, potassium, folate, and B vitamins. Dried kidney beans provide energy, support blood health, and can be preferred as part of a healthy diet.", FoodPicture = "../../../images/foodimages/barbunya.jfif", Amount = 100 },
            new Food { FoodID = 19, FoodName = "Fresh Peas", FoodCategoryID = 3, Protein = 2.2, Carbonhydrate = 8.7, Fat = 0.2, Calorie = 47, Description = "Fresh green peas are a highly nutritious vegetable that is packed with vitamins, minerals, fiber, and antioxidants. They are a rich source of vitamin C, vitamin K, vitamin B6, folate, and iron. Green peas also provide dietary fiber, which aids in digestion and helps maintain a healthy weight. They are low in calories and contain plant-based protein. Additionally, green peas offer numerous health benefits, including supporting heart health, boosting the immune system, and promoting eye health.", FoodPicture = "../../../images/foodimages/tazebezelye.jfif", Amount = 100 },
            new Food { FoodID = 20, FoodName = "Green Pepper", FoodCategoryID = 3, Protein = 1.2, Carbonhydrate = 5.7, Fat = 0.2, Calorie = 25, Description = "Green bell pepper is a low-calorie vegetable that is rich in vitamins C, A, fiber, and antioxidants. It also contains important nutrients such as B vitamins, potassium, and iron. Green bell pepper supports the immune system, improves digestive health, and preserves eye health. Additionally, it may assist with weight management and contribute to overall well-being.", FoodPicture = "../../../images/foodimages/yeşilbiber.jfif", Amount = 100 },
            new Food { FoodID = 21, FoodName = "Brussels Sprouts", FoodCategoryID = 3, Protein = 4.4, Carbonhydrate = 8.9, Fat = 0.5, Calorie = 47, Description = "Brussels sprouts are a low-calorie vegetable that is high in fiber, vitamin C, vitamin K, and folate. It also contains important minerals such as potassium, iron, and magnesium. Brussels sprouts support the immune system, improve digestive health, and maintain bone health. They are also known for their antioxidant properties and overall health benefits.", FoodPicture = "../../../images/foodimages/bruksellahana.jfif", Amount = 100 },
            new Food { FoodID = 22, FoodName = "Tomato", FoodCategoryID = 3, Protein = 1, Carbonhydrate = 1, Fat = 0.3, Calorie = 25, Description = "Tomato is a low-calorie fruit that is rich in vitamins C, A, potassium, and antioxidants such as lycopene. It also supports digestion with its fiber content. Tomato helps maintain heart health, supports eye health, and strengthens the immune system. Additionally, it may have protective effects against cancer.", FoodPicture = "../../../images/foodimages/domates.jfif", Amount = 100 },
            new Food { FoodID = 23, FoodName = "Artichoke", FoodCategoryID = 3, Protein = 2.9, Carbonhydrate = 11.9, Fat = 0.4, Calorie = 63, Description = "Artichoke is a low-calorie vegetable that is high in fiber, vitamin C, folate, and potassium. It also contains antioxidants and flavonoids. Artichoke supports digestive health, helps lower cholesterol levels, boosts the immune system, and promotes liver health. Additionally, it may assist in blood sugar control and has anti-inflammatory effects.", FoodPicture = "../../../images/foodimages/enginar.jfif", Amount = 100 },
            new Food { FoodID = 24, FoodName = "Dried Beans", FoodCategoryID = 3, Protein = 20.7, Carbonhydrate = 1.3, Fat = 61.6, Calorie = 333, Description = "Dried kidney beans are a nutritious legume that is high in protein, fiber, vitamins, and minerals. Protein supports muscle development and repair, while fiber aids in digestion and provides a feeling of fullness. It also contains important nutrients such as iron, magnesium, potassium, and B vitamins. Dried kidney beans provide energy, support blood health, and can be preferred as part of a healthy diet.", FoodPicture = "../../../images/foodimages/kurufasulye.jfif", Amount = 100 },
            new Food { FoodID = 25, FoodName = "Beans", FoodCategoryID = 3, Protein = 2.4, Carbonhydrate = 0.2, Fat = 7.7, Calorie = 35, Description = "Fresh green beans are a highly nutritious vegetable that is low in calories and rich in fiber. They are a great source of vitamins A, C, and K, as well as folate and manganese. Green beans also provide essential minerals like potassium and iron. They promote digestion, support heart health, and contribute to maintaining strong bones. Additionally, they are packed with antioxidants and offer numerous health benefits, including immune system support and overall well-being.", FoodPicture = "../../../images/foodimages/tazefasulye.jfif", Amount = 100 },
            new Food { FoodID = 26, FoodName = "Carrot", FoodCategoryID = 3, Protein = 1.2, Carbonhydrate = 9.3, Fat = 0.3, Calorie = 42, Description = "Carrot is a nutritious vegetable that is high in vitamin A, fiber, and antioxidants. It also contains important nutrients such as vitamin C, vitamin K, potassium, and iron. Carrot supports eye health, strengthens the immune system, and improves digestion. Additionally, it promotes skin health and is heart-friendly.", FoodPicture = "../../../images/foodimages/havuc.jfif", Amount = 100 },
            new Food { FoodID = 27, FoodName = "Cucumber", FoodCategoryID = 3, Protein = 1, Carbonhydrate = 1, Fat = 0, Calorie = 8, Description = "Cucumber is a low-calorie vegetable that is high in water content and rich in fiber. It contains important nutrients such as vitamin A, vitamin C, vitamin K, and potassium. Cucumber supports hydration, improves digestive health, and promotes skin health. It also adds freshness and flavor to many dishes and salads.", FoodPicture = "../../../images/foodimages/salatalık.jfif", Amount = 100 },
            new Food { FoodID = 28, FoodName = "Spinach", FoodCategoryID = 3, Protein = 2.3, Carbonhydrate = 3.2, Fat = 0.3, Calorie = 25, Description = "Spinach is a low-calorie leafy vegetable that is rich in various nutrients. It contains iron, calcium, vitamin A, vitamin C, fiber, and antioxidants. Spinach supports bone health, preserves eye health, boosts the immune system, and aids in digestion. Additionally, it may help regulate blood pressure and possess anti-aging properties.", FoodPicture = "../../../images/foodimages/ıspanak.jfif", Amount = 100 },
            new Food { FoodID = 29, FoodName = "Zucchini", FoodCategoryID = 3, Protein = 0.6, Carbonhydrate = 3.9, Fat = 0.1, Calorie = 19, Description = "Zucchini, a low-calorie vegetable, is rich in fiber, vitamin C, vitamin A, and potassium. Its fiber content supports digestive health, while vitamin C strengthens the immune system. Vitamin A contributes to eye health, and potassium supports healthy blood pressure levels. Zucchini can be preferred as part of a healthy diet and can be used in various dishes.", FoodPicture = "../../../images/foodimages/kabak.jfif", Amount = 100 },
            new Food { FoodID = 30, FoodName = "Cauliflower", FoodCategoryID = 3, Protein = 2.4, Carbonhydrate = 4.9, Fat = 0.2, Calorie = 25, Description = "Cauliflower is a vegetable that belongs to the brassica family and provides a nutritious profile. Its essential nutritional values include fiber, vitamin C, folate, vitamin K, vitamin B6, potassium, and magnesium. Additionally, cauliflower is a low-calorie vegetable with low carbohydrate and fat content. Its high fiber content supports digestive health, and its richness in antioxidants is beneficial for the body. Cauliflower is known as a vegetable that can contribute to a healthy diet.", FoodPicture = "../../../images/foodimages/karnabahar.jfif", Amount = 100 },
            new Food { FoodID = 31, FoodName = "Celery", FoodCategoryID = 3, Protein = 2, Carbonhydrate = 7, Fat = 0, Calorie = 38, Description = "Celery is a root vegetable. Its nutritional values include vitamins C, K, B6, potassium, calcium, fiber, and antioxidants. It is a healthy, low-calorie vegetable that aids digestion.", FoodPicture = "../../../images/foodimages/kereviz.jfif", Amount = 100 },
            new Food { FoodID = 32, FoodName = "Red Beet", FoodCategoryID = 3, Protein = 1.6, Carbonhydrate = 9.6, Fat = 0.1, Calorie = 42, Description = "Red beetroot is a root vegetable that is commonly used in salads. It is rich in fiber, vitamin C, iron, and folate. It also contains important minerals such as potassium, manganese, magnesium, and B vitamins. Red beetroot is a low-calorie food that aids digestion and supports digestive health. It is also known for its antioxidant properties, which boost the immune system and prevent cell damage.", FoodPicture = "../../../images/foodimages/kırmızıpancar.jfif", Amount = 100 },
            new Food { FoodID = 33, FoodName = "Cabbage", FoodCategoryID = 3, Protein = 1.4, Carbonhydrate = 5.3, Fat = 0.2, Calorie = 24, Description = "Cabbage is a leafy green vegetable that provides a nutritious profile. It contains nutrients such as vitamin C, vitamin K, fiber, folate, iron, and calcium. It is also rich in antioxidants and phytochemicals. Cabbage supports digestion, boosts the immune system, and helps reduce the risk of cancer.", FoodPicture = "../../../images/foodimages/lahana.jfif", Amount = 100 },
            new Food { FoodID = 34, FoodName = "Mushroom", FoodCategoryID = 3, Protein = 2.4, Carbonhydrate = 0.4, Fat = 0.3, Calorie = 16, Description = "Mushrooms are low in calories and fat, but rich in protein, fiber, vitamins, and minerals. They can aid in weight management, boost the immune system, and support digestive health. However, caution is needed as some mushrooms can be toxic. Consult a healthcare professional if you have any health concerns or allergies related to mushrooms.", FoodPicture = "../../../images/foodimages/mantar.jfif", Amount = 100 },
            new Food { FoodID = 35, FoodName = "Lettuce", FoodCategoryID = 3, Protein = 1.2, Carbonhydrate = 2.9, Fat = 0.2, Calorie = 15, Description = "Lettuce, in short with its nutritional values, is a leafy vegetable that is low in calories and high in water and fiber content. It also contains vitamins A, C, and K, as well as minerals like folate, iron, and potassium. Lettuce is commonly used in salads and sandwiches and can be an important part of a healthy eating plan.", FoodPicture = "../../../images/foodimages/marul.jfif", Amount = 100 },
            new Food { FoodID = 36, FoodName = "Lentils", FoodCategoryID = 3, Protein = 23.7, Carbonhydrate = 57.4, Fat = 1.3, Calorie = 351, Description = "Kuru mercimek (lentils) is a nutritious legume that contains protein, fiber, vitamins, and minerals. It is rich in protein and fiber, providing energy to the body and supporting the digestive system. Additionally, it contains important nutrients such as iron, folate, potassium, and B vitamins. Kuru mercimek can be preferred as part of a healthy diet and can be used in various dishes.", FoodPicture = "../../../images/foodimages/mercimek kuru.jfif", Amount = 100 },
            new Food { FoodID = 37, FoodName = "Chickpeas", FoodCategoryID = 3, Protein = 19.2, Carbonhydrate = 56.7, Fat = 6.2, Calorie = 376, Description = "Chickpeas, also known as garbanzo bean, is a legume that is highly nutritious. It contains important nutrients such as protein, fiber, iron, magnesium, phosphorus, B vitamins, and folate. Chickpeas help regulate digestion, lower cholesterol levels, provide energy, support muscle development, and strengthen the immune system. They may also be beneficial for maintaining a healthy weight.", FoodPicture = "../../../images/foodimages/nohut.jfif", Amount = 100 },
            new Food { FoodID = 38, FoodName = "Beet", FoodCategoryID = 3, Protein = 1.6, Carbonhydrate = 9.6, Fat = 0.1, Calorie = 42, Description = "Beets are a low-calorie root vegetable that provides numerous nutritional benefits. They are high in fiber, vitamins (C, B6, and folate), and minerals (potassium). Additionally, beets are a rich source of antioxidants, which help reduce cell damage by combating free radicals. As a result, incorporating beets into a healthy diet can support digestive health, boost the immune system, and improve cardiovascular health.", FoodPicture = "../../../images/foodimages/pancar.jfif", Amount = 100 },
            new Food { FoodID = 39, FoodName = "Potato", FoodCategoryID = 3, Protein = 2, Carbonhydrate = 19.1, Fat = 0.1, Calorie = 83, Description = "Potato is a root vegetable that is rich in starch. It also contains several essential nutrients. Potatoes are high in carbohydrates, proteins, fiber, vitamins (such as vitamin C and vitamin B6), and minerals (such as potassium and manganese). They are also low in fat. Potatoes provide energy, support the digestive system, and strengthen the immune system.", FoodPicture = "../../../images/foodimages/patates.jfif", Amount = 100 },
            new Food { FoodID = 40, FoodName = "Eggplant", FoodCategoryID = 3, Protein = 1.1, Carbonhydrate = 5.5, Fat = 0.2, Calorie = 24, Description = "Eggplant is a low-calorie vegetable that contains carbohydrates, fiber, vitamins, and minerals. It also contains antioxidants.", FoodPicture = "../../../images/foodimages/patlıcan.jfif", Amount = 100 },
            new Food { FoodID = 41, FoodName = "Chard", FoodCategoryID = 3, Protein = 2.6, Carbonhydrate = 4.8, Fat = 0.4, Calorie = 27, Description = "Chard is a nutritious leafy vegetable. It contains high amounts of fiber, iron, calcium, and vitamins A and K.", FoodPicture = "../../../images/foodimages/pazı.jfif", Amount = 100 },
            new Food { FoodID = 42, FoodName = "Leek", FoodCategoryID = 3, Protein = 1.8, Carbonhydrate = 1.8, Fat = 0.2, Calorie = 52, Description = "Leek is a nutritious vegetable. It contains nutrients such as fiber, vitamin C, vitamin K, folate, and potassium.", FoodPicture = "../../../images/foodimages/pırasa.jfif", Amount = 100 },
            new Food { FoodID = 43, FoodName = "Purslane", FoodCategoryID = 3, Protein = 2, Carbonhydrate = 3.8, Fat = 0.4, Calorie = 32, Description = "Purslane is a green leafy vegetable that is commonly used in salads. It is a low-calorie food and contains rich amounts of vitamins, minerals, and fiber. Purslane is particularly high in vitamins A, C, K, and minerals such as iron, calcium, and magnesium. It also contains antioxidants and can support the immune system. Purslane can help regulate the digestive system, promote digestive health, and be beneficial in weight loss processes.", FoodPicture = "../../../images/foodimages/semizotu.jfif", Amount = 100 },

            new Food { FoodID = 44, FoodName = "Wheat Bread", FoodCategoryID = 4, Protein = 7.2, Carbonhydrate = 53.1, Fat = 1.1, Calorie = 247, Description = "Wheat bread is a type of bread made from wheat flour, water, yeast, and salt, among other basic ingredients. Wheat bread contains various nutrients such as carbohydrates, protein, fiber, vitamins, and minerals. However, the nutritional values may vary depending on the bread-making process, the type of flour used, and other additional ingredients. Generally, wheat bread is a healthy source of energy and is a staple in many diets.", FoodPicture = "../../../images/foodimages/bugdayekmegı.jfif", Amount = 100 },
            new Food { FoodID = 45, FoodName = "Bulgur Wheat", FoodCategoryID = 4, Protein = 12.5, Carbonhydrate = 69.8, Fat = 1.5, Calorie = 350, Description = "Bulgur, a grain obtained by grinding and cleaning wheat, is a food with high nutritional value. It contains complex carbohydrates, fiber, protein, vitamins, and minerals. Bulgur's fibrous structure slows down digestion and provides a feeling of satiety. It can also help regulate calorie intake due to its low fat content. With its iron, magnesium, phosphorus, B vitamins, and folate, Bulgur provides important support for the body. Moreover, Bulgur is a preferred food in a healthy diet due to its low glycemic index value.", FoodPicture = "../../../images/foodimages/bulgur.jfif", Amount = 100 },
            new Food { FoodID = 46, FoodName = "Noodle", FoodCategoryID = 4, Protein = 7.7, Carbonhydrate = 76, Fat = 5, Calorie = 390, Description = "Erişte, commonly known as 'noodles' in English, is a type of pasta typically made from flour, eggs, and water. Its nutritional values vary depending on the ingredients used and the specific recipe. Generally, erişte is a carbohydrate-rich pasta and can be a source of protein, vitamins, and minerals. In summary, erişte is a type of pasta high in carbohydrates and may contain protein, vitamins, and minerals.", FoodPicture = "../../../images/foodimages/erişte.jfif", Amount = 100 },
            new Food { FoodID = 47, FoodName = "Pasta", FoodCategoryID = 4, Protein = 7.7, Carbonhydrate = 76, Fat = 5, Calorie = 390, Description = "Pasta, commonly served in various shapes, is a light and filling food. Carbohydrates provide energy to the body, and pasta meets this need. Protein content contributes to muscle strength and recovery. Fiber supports the digestive system and provides a feeling of fullness. B vitamins are important for metabolism and can be found in pasta. Additionally, there can be variations in mineral content among different types of pasta.", FoodPicture = "../../../images/foodimages/makarna.jfif", Amount = 100 },
            new Food { FoodID = 48, FoodName = "Corn", FoodCategoryID = 4, Protein = 9.4, Carbonhydrate = 72, Fat = 2.2, Calorie = 351, Description = "Corn is a high-carbohydrate grain that contains fiber, vitamins A and C, folate, magnesium, and potassium.", FoodPicture = "../../../images/foodimages/mısır.jfif", Amount = 100 },
            new Food { FoodID = 49, FoodName = "Cornflour", FoodCategoryID = 4, Protein = 9, Carbonhydrate = 74, Fat = 1.4, Calorie = 353, Description = "Corn flour is a type of flour obtained by grinding corn. It contains high amounts of carbohydrates and dietary fiber. Carbohydrates are used as an energy source, while fiber helps regulate the digestive system.", FoodPicture = "../../../images/foodimages/mısır unu.jfif", Amount = 100 },
            new Food { FoodID = 50, FoodName = "Starch", FoodCategoryID = 4, Protein = 10, Carbonhydrate = 74, Fat = 1, Calorie = 353, Description = "Starch is a type of carbohydrate found in plants. It is a significant source of energy for humans and is converted into glucose during digestion. Starch is commonly found in grains (such as wheat, rice, and corn), potatoes, corn, and some legumes. Its nutritional value typically includes the amount of carbohydrates it contains, providing energy. Other nutrients such as protein, fat, vitamins, and minerals are present in lower quantities in starch.", FoodPicture = "../../../images/foodimages/nişasta.jfif", Amount = 100 },
            new Food { FoodID = 51, FoodName = "Rice", FoodCategoryID = 4, Protein = 3.5, Carbonhydrate = 39.5, Fat = 21, Calorie = 368, Description = "Pilav, rice or other grains cooked with water, is a dish obtained by boiling them. Its nutritional values may vary depending on the type of rice, cooking method, and other ingredients used. Generally, pilaf contains carbohydrates, proteins, fibers, and some minerals. However, the nutritional content of pilaf can vary based on the ingredients used and serving size.", FoodPicture = "../../../images/foodimages/pilav.jfif", Amount = 100 },
            new Food { FoodID = 52, FoodName = "Rice Flour", FoodCategoryID = 4, Protein = 10, Carbonhydrate = 74, Fat = 1, Calorie = 353, Description = "Rice Flour is a type of flour obtained by grinding rice grains. It contains carbohydrates, protein, fiber, and various minerals. It provides energy, serves as building blocks for the body, regulates the digestive system, and contains important minerals. It is commonly used in various recipes.", FoodPicture = "../../../images/foodimages/pirinçubu.jfif", Amount = 100 },
            new Food { FoodID = 53, FoodName = "Vermicelli", FoodCategoryID = 4, Protein = 7.7, Carbonhydrate = 76, Fat = 5, Calorie = 390, Description = "Tel Şehriye is a type of thin and long noodle in Middle Eastern cuisine. It is used in dishes such as pilaf, soup, salad, and dessert. It is a quick, convenient, and flavorful option.", FoodPicture = "../../../images/foodimages/tel şehriye.jfif", Amount = 100 },
            new Food { FoodID = 54, FoodName = "Tarhana", FoodCategoryID = 4, Protein = 14.1, Carbonhydrate = 58.8, Fat = 3.9, Calorie = 329, Description = "Tarhanyi is a traditional Central Asian dish. This dish is made by processing the grains of a plant called 'Tarhun' which is typically composed of wheat and chickpeas. Tarhanyi is a nutrient-rich food in terms of basic nutritional values. It is a good source of protein, fiber, iron, and B vitamins. It is also a healthy option due to its low fat and cholesterol content.", FoodPicture = "../../../images/foodimages/tarhana.jfif", Amount = 100 },
            new Food { FoodID = 55, FoodName = "Oat Flour", FoodCategoryID = 4, Protein = 14, Carbonhydrate = 66, Fat = 7, Calorie = 402, Description = "Oat flour is a type of flour made by grinding oats. It is known for its high fiber content, low glycemic index, and rich nutrient profile. Oat flour is rich in complex carbohydrates, protein, fiber, vitamins (especially B vitamins), and minerals (such as manganese, phosphorus, magnesium, and zinc). Additionally, oat flour contains a type of soluble fiber called beta-glucan, which provides digestive health benefits. Oat flour can be used as part of a healthy diet and can contribute to nutrition in various recipes.", FoodPicture = "../../../images/foodimages/yulafunu.jfif", Amount = 100 },

            new Food { FoodID = 56, FoodName = "Whole Egg", FoodCategoryID = 5, Protein = 8, Carbonhydrate = 0, Fat = 6, Calorie = 155.1, Description = "Egg is a nutritious food that contains high levels of protein, healthy fats, vitamins (A, D, E, K, B2, B6, B12, folate), and minerals (iron, zinc, selenium, phosphorus). It also contains antioxidants that support eye health.", FoodPicture = "../../../images/foodimages/yumurta.jfif", Amount = 100 },
            new Food { FoodID = 57, FoodName = "Egg Yolk", FoodCategoryID = 5, Protein = 17, Carbonhydrate = 0, Fat = 33, Calorie = 377, Description = "Egg yolk: It contains high protein, healthy fats, vitamins (A, D, E, K, B), and minerals (iron, selenium, zinc, phosphorus).", FoodPicture = "../../../images/foodimages/yumurtasarısı.jfif", Amount = 100 },
            new Food { FoodID = 58, FoodName = "Egg Whites", FoodCategoryID = 5, Protein = 11, Carbonhydrate = 1, Fat = 33, Calorie = 49, Description = "Egg white is a low-calorie and fat-free source of protein. It contains essential amino acids, B vitamins, and minerals. It is cholesterol-free and important for muscle development, repair, and tissue regeneration.", FoodPicture = "../../../images/foodimages/yumurtaakı.jfif", Amount = 100 },

            new Food { FoodID = 59, FoodName = "Breast Milk", FoodCategoryID = 6, Protein = 1, Carbonhydrate = 6.9, Fat = 4.4, Calorie = 70, Description = "Breast milk is the most suitable and nutritious source of food for a baby's healthy growth and development. It contains all the necessary nutrients for the baby and is easily digested. Additionally, breast milk contains special components such as antibodies that strengthen the immune system, enzymes that aid digestion, and omega-3 fatty acids that support brain development. Furthermore, breast milk helps mature the baby's digestive system and promotes a healthy gut flora. The nutritional composition of breast milk may vary depending on the baby's growth stage.", FoodPicture = "../../../images/foodimages/annesütü.jfif", Amount = 100 },
            new Food { FoodID = 60, FoodName = "Feta Cheese (Full Fat)", FoodCategoryID = 6, Protein = 22.5, Carbonhydrate = 2.1, Fat = 21.6, Calorie = 289, Description = "Feta cheese is a type of white cheese that is typically made from milk. It is rich in nutritional value and contains several important nutrients. Feta cheese is generally high in protein, calcium, phosphorus, sodium, potassium, and B vitamins. It also has low fat and carbohydrate content. In summary, feta cheese is a cheese type that is rich in protein, calcium, and other essential nutrients.", FoodPicture = "../../../images/foodimages/beyaz peynir.jfif", Amount = 100 },
            new Food { FoodID = 61, FoodName = "Feta Cheese (Low Fat)", FoodCategoryID = 6, Protein = 19, Carbonhydrate = 3.8, Fat = 0.7, Calorie = 99, Description = "Feta cheese is a type of white cheese that is typically made from milk. It is rich in nutritional value and contains several important nutrients. Feta cheese is generally high in protein, calcium, phosphorus, sodium, potassium, and B vitamins. It also has low fat and carbohydrate content. In summary, feta cheese is a cheese type that is rich in protein, calcium, and other essential nutrients.", FoodPicture = "../../../images/foodimages/beyaz peynir.jfif", Amount = 100 },
            new Food { FoodID = 62, FoodName = "Milk (Fat)", FoodCategoryID = 6, Protein = 3.3, Carbonhydrate = 4.7, Fat = 3.3, Calorie = 61, Description = "Cow's milk is a nutrient-rich food that contains high-quality protein, a carbohydrate called lactose, fats, vitamins such as A, D, E, K, and minerals like calcium and phosphorus. Proteins are essential building blocks for the body, carbohydrates provide energy, and fats aid in the absorption of vitamins. The vitamins and minerals in cow's milk are necessary for eye health, bone development, nerve transmission, and other metabolic processes.", FoodPicture = "../../../images/foodimages/ineksütü.jfif", Amount = 100 },
            new Food { FoodID = 63, FoodName = "Milk (Semi-skimmed)", FoodCategoryID = 6, Protein = 3.3, Carbonhydrate = 4.8, Fat = 1.9, Calorie = 50, Description = "Cow's milk is a nutrient-rich food that contains high-quality protein, a carbohydrate called lactose, fats, vitamins such as A, D, E, K, and minerals like calcium and phosphorus. Proteins are essential building blocks for the body, carbohydrates provide energy, and fats aid in the absorption of vitamins. The vitamins and minerals in cow's milk are necessary for eye health, bone development, nerve transmission, and other metabolic processes.", FoodPicture = "../../../images/foodimages/ineksütü.jfif", Amount = 100 },
            new Food { FoodID = 64, FoodName = "Milk (Skim)", FoodCategoryID = 6, Protein = 3.4, Carbonhydrate = 4.9, Fat = 0.2, Calorie = 35, Description = "Cow's milk is a nutrient-rich food that contains high-quality protein, a carbohydrate called lactose, fats, vitamins such as A, D, E, K, and minerals like calcium and phosphorus. Proteins are essential building blocks for the body, carbohydrates provide energy, and fats aid in the absorption of vitamins. The vitamins and minerals in cow's milk are necessary for eye health, bone development, nerve transmission, and other metabolic processes.", FoodPicture = "../../../images/foodimages/ineksütü.jfif", Amount = 100 },
            new Food { FoodID = 65, FoodName = "Cheese", FoodCategoryID = 6, Protein = 27, Carbonhydrate = 1.4, Fat = 31.7, Calorie = 349, Description = "Kashar cheese is a type of cheese typically made from cow's milk. It is a rich source of nutrients. It contains protein, fat, calcium, phosphorus, sodium, potassium, vitamin B, and vitamin A. However, Kashar cheese is a high-calorie food and should be consumed in moderation due to its saturated fat content. The nutritional values may vary depending on the production process, brand, and other factors.", FoodPicture = "../../../images/foodimages/kaşarpeynir.jfif", Amount = 100 },
            new Food { FoodID = 66, FoodName = "Cream %30", FoodCategoryID = 6, Protein = 2, Carbonhydrate = 3, Fat = 30, Calorie = 302, Description = "Clotted cream is a dairy product with a high fat content that rises to the surface of milk and is collected. It is a rich source of nutrients and is typically a high-calorie food. Clotted cream contains fat, protein, calcium, phosphorus, and vitamins A and D. However, excessive consumption can lead to weight gain and increased cholesterol levels, so it is recommended to consume it in moderation.", FoodPicture = "../../../images/foodimages/kaymak.jfif", Amount = 100 },
            new Food { FoodID = 67, FoodName = "Goat's Milk", FoodCategoryID = 6, Protein = 3.6, Carbonhydrate = 4.5, Fat = 4.1, Calorie = 69, Description = "Goat milk is a nutritious liquid that contains protein, fat, carbohydrates, vitamins, and minerals. Its protein content helps with the development of muscles and tissues, while fat plays a role in providing energy. Goat milk also contains important nutrients such as vitamin A, calcium, phosphorus, and riboflavin. However, individual nutritional needs vary, so it should be consumed considering personal health conditions and tolerances.", FoodPicture = "../../../images/foodimages/kecisütü.jfif", Amount = 100 },
            new Food { FoodID = 68, FoodName = "Ewe Milk", FoodCategoryID = 6, Protein = 6, Carbonhydrate = 5.4, Fat = 7, Calorie = 108, Description = "Sheep milk is a food that contains essential nutrients such as protein, fat, and carbohydrates. Proteins are important for the growth and repair of the body, fats provide energy and assist in the absorption of fat-soluble vitamins, while carbohydrates serve as a source of energy. In addition to these nutrients, sheep milk also contains other minerals and vitamins.", FoodPicture = "../../../images/foodimages/koyunsütü.jfif", Amount = 100 },
            new Food { FoodID = 69, FoodName = "Cream %20", FoodCategoryID = 6, Protein = 2.9, Carbonhydrate = 3.7, Fat = 20, Calorie = 204, Description = "Cream is a dense and sweet dairy product with a high fat content. Its nutritional values can be summarized as follows: calories (typically 300-400 calories/100g), fat (30-40%), protein (low amount), and carbohydrates (low amount). It is important to consume cream in moderation.", FoodPicture = "../../../images/foodimages/krema.jfif", Amount = 100 },
            new Food { FoodID = 70, FoodName = "Water Buffalo", FoodCategoryID = 6, Protein = 3.8, Carbonhydrate = 5.2, Fat = 6.9, Calorie = 97, Description = "Manda milk is a nutritious type of milk with high protein, fat, lactose, vitamins, and minerals content. Its high protein content is important for growth and development, fats provide energy, and vitamins and minerals contribute to regulating bodily functions.", FoodPicture = "../../../images/foodimages/mandasütü.jfif", Amount = 100 },
            new Food { FoodID = 71, FoodName = "Yoghurt (Full Fat)", FoodCategoryID = 6, Protein = 3.5, Carbonhydrate = 4.7, Fat = 3.3, Calorie = 61, Description = "Yogurt: Fermented dairy product. It contains high levels of protein, calcium, vitamins, and probiotics. It is beneficial for a healthy diet, bone health, digestion, and immune system.", FoodPicture = "../../../images/foodimages/yogurt.jfif", Amount = 100 },
            new Food { FoodID = 72, FoodName = "Yoghurt (Half Fat)", FoodCategoryID = 6, Protein = 5.3, Carbonhydrate = 7, Fat = 1.6, Calorie = 63, Description = "Yogurt: Fermented dairy product. It contains high levels of protein, calcium, vitamins, and probiotics. It is beneficial for a healthy diet, bone health, digestion, and immune system.", FoodPicture = "../../../images/foodimages/yogurt.jfif", Amount = 100 },
            new Food { FoodID = 73, FoodName = "Yoghurt (Fatless)", FoodCategoryID = 6, Protein = 5.7, Carbonhydrate = 7.7, Fat = 0.2, Calorie = 56, Description = "Yogurt: Fermented dairy product. It contains high levels of protein, calcium, vitamins, and probiotics. It is beneficial for a healthy diet, bone health, digestion, and immune system.", FoodPicture = "../../../images/foodimages/yogurt.jfif", Amount = 100 },

            new Food { FoodID = 74, FoodName = "Pear", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 13, Fat = 0, Calorie = 57, Description = "Pear is a highly nutritious fruit. It is a rich source of dietary fiber, vitamins (especially vitamin C), and minerals that are important for the body's energy needs. Pear also contains antioxidants and supports the digestive system, improving gut health. In summary, pear is a valuable option for a healthy diet.", FoodPicture = "../../../images/foodimages/armut.jfif", Amount = 100 },
            new Food { FoodID = 75, FoodName = "Strawberry", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 8, Fat = 0, Calorie = 39, Description = "Strawberries are low-calorie fruits that contain various nutrients. They are rich in vitamin C, fiber, folate, potassium, and antioxidants. Vitamin C supports the immune system, while antioxidants protect cells from free radicals. Fiber improves digestion and provides a feeling of fullness. Folate is important for cell renewal and DNA synthesis. Potassium helps regulate muscle functions and blood pressure.", FoodPicture = "../../../images/foodimages/çilek.jfif", Amount = 100 },
            new Food { FoodID = 76, FoodName = "Apple", FoodCategoryID = 7, Protein = 0, Carbonhydrate = 12, Fat = 0, Calorie = 52, Description = "An apple is a nutritious fruit that is typically round or flat in shape. Its skin is usually shiny red, green, or yellow in color. The inside of an apple is juicy and sweet. In terms of nutritional value, an apple is a low-calorie fruit and is rich in fiber, vitamin C, potassium, and antioxidants. Its fiber content supports digestive health and provides a feeling of fullness. Vitamin C strengthens the immune system, and antioxidants protect the body against the harmful effects of free radicals.", FoodPicture = "../../../images/foodimages/elma.jfif", Amount = 100 },
            new Food { FoodID = 77, FoodName = "Plum", FoodCategoryID = 7, Protein = 5, Carbonhydrate = 18, Fat = 0.2, Calorie = 65, Description = "Plum is a fruit belonging to the Prunus genus. It contains nutrients such as water, fiber, vitamin C, vitamin A, potassium, and iron. It also contains phenolic compounds that have antioxidant properties and other health benefits.", FoodPicture = "../../../images/foodimages/erik.jfif", Amount = 100 },
            new Food { FoodID = 78, FoodName = "Fig", FoodCategoryID = 7, Protein = 1.2, Carbonhydrate = 20.4, Fat = 0.2, Calorie = 65, Description = "Fig is a sweet and soft fruit. It is considered a rich source of nutrients. Fig is abundant in terms of dietary fiber, vitamins (A, B6, C, and K), minerals (potassium, calcium, iron, and magnesium), and antioxidants. Additionally, figs naturally contain sugar.", FoodPicture = "../../../images/foodimages/incir.jfif", Amount = 100 },
            new Food { FoodID = 79, FoodName = "Mulberry", FoodCategoryID = 7, Protein = 6.9, Carbonhydrate = 19.8, Fat = 1.1, Calorie = 93, Description = "Mulberry is a fruit that is especially grown in hot climates. Mulberries are usually black in color and have a small, round structure. It is a highly nutritious fruit with its rich content of nutrients.", FoodPicture = "../../../images/foodimages/karadut.jfif", Amount = 100 },
            new Food { FoodID = 80, FoodName = "Watermelon", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 5, Fat = 0, Calorie = 93, Description = "Watermelon is a summer fruit that is consumed. It is low in calories due to its high water content. It contains antioxidants such as vitamin C, vitamin A, and lycopene. It also provides minerals like potassium, magnesium, and B vitamins. It supports digestive health, promotes hydration, and offers some health benefits. However, it can rapidly increase blood sugar, so individuals with diabetes should exercise caution.", FoodPicture = "../../../images/foodimages/karpuz.jfif", Amount = 100 },
            new Food { FoodID = 81, FoodName = "Cantaloupe", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 6, Fat = 0, Calorie = 28, Description = "Cantaloupe is a fruit that grows in the summer season. It is rich in nutritional values and is a low-calorie fruit. The carbohydrates it contains provide energy to the body. Additionally, cantaloupe is also rich in fiber, contributing to digestive health.", FoodPicture = "../../../images/foodimages/kavun.jfif", Amount = 100 },
            new Food { FoodID = 82, FoodName = "Apricot", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 12, Fat = 0, Calorie = 54, Description = "Apricot is a fiber-rich fruit that supports digestive health. It also contains vitamins A, C, E, K and minerals such as potassium, iron, and magnesium. These nutrients support the health of bones and tissues, strengthen the immune system, and aid in proper bodily functions.", FoodPicture = "../../../images/foodimages/kayısı.jfif", Amount = 100 },
            new Food { FoodID = 83, FoodName = "Cherry", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 13, Fat = 0, Calorie = 57, Description = "Cherry: Small, round, red fruit. Nutritional values: Vitamin C, Vitamin A, Vitamin K, potassium, iron, manganese.", FoodPicture = "../../../images/foodimages/kiraz.jfif", Amount = 100 },
            new Food { FoodID = 84, FoodName = "Lemon", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 3.2, Fat = 0, Calorie = 17, Description = "Lemon is a fruit belonging to the citrus family and is generally known for its pleasant aroma and sour taste. In terms of nutritional value, lemons are low in calories and rich in vitamin C, fiber, and some minerals.", FoodPicture = "../../../images/foodimages/limon.jfif", Amount = 100 },
            new Food { FoodID = 85, FoodName = "Mandarin Orange", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 8, Fat = 0, Calorie = 6, Description = "Mandarin is a fruit belonging to the citrus family and is commonly consumed during the winter season. Mandarin is rich in various nutrients such as vitamin C, fiber, potassium, and antioxidants. It is also known as a low-calorie fruit. Vitamin C supports the immune system, while fiber promotes digestive health and provides a feeling of fullness. Potassium helps maintain normal muscle function, blood pressure, and fluid balance in the body. Antioxidants can help reduce the effects of harmful free radicals on cells.", FoodPicture = "../../../images/foodimages/mandalina.jfif", Amount = 100 },
            new Food { FoodID = 86, FoodName = "Banana", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 21, Fat = 0, Calorie = 90, Description = "Nutritional values are values that provide information about the nutrients present in food. These values are important for understanding the impact of food on health, creating a balanced diet plan, and meeting the body's nutritional needs. ", FoodPicture = "../../../images/foodimages/muz.jfif", Amount = 100 },
            new Food { FoodID = 87, FoodName = "Pomegranate", FoodCategoryID = 7, Protein = 0.8, Carbonhydrate = 14.7, Fat = 0.7, Calorie = 77, Description = "Pomegranate, which belongs to the Punica genus in the order Cucurbitales, is a fruit known for its unique taste and flavor. It is also a highly nutritious fruit. Its key nutritional components include vitamin C, vitamin B, potassium, fiber, and antioxidants.", FoodPicture = "../../../images/foodimages/nar.jfif", Amount = 100 },
            new Food { FoodID = 88, FoodName = "Orange", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 9, Fat = 0, Calorie = 41, Description = "Orange is a fruit belonging to the citrus family. It contains a high amount of vitamin C, which strengthens the immune system. Additionally, it is rich in fiber, which regulates the digestive system and provides a feeling of satiety.", FoodPicture = "../../../images/foodimages/portakal.jfif", Amount = 100 },
            new Food { FoodID = 89, FoodName = "Peach", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 11, Fat = 0, Calorie = 49, Description = "Peach is a sweet and juicy fruit. It contains nutrients such as vitamin C, vitamin A, vitamin E, vitamin K, potassium, magnesium, and iron. Additionally, it is rich in dietary fiber. The nutritional values of peach provide several benefits, including strengthening the immune system, supporting eye health, regulating blood pressure, promoting bone health, and aiding digestion.", FoodPicture = "../../../images/foodimages/şeftali.jfif", Amount = 100 },
            new Food { FoodID = 90, FoodName = "Grape", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 17, Fat = 0, Calorie = 74, Description = "Grape is a fruit belonging to the Vitis genus and is widely cultivated worldwide. It usually comes in two different varieties, sweet and sour. Grape is a nutritious fruit that contains various vitamins, minerals, and other essential nutrients.", FoodPicture = "../../../images/foodimages/üzüm.jfif", Amount = 100 },
            new Food { FoodID = 91, FoodName = "Sour Cherry", FoodCategoryID = 7, Protein = 1, Carbonhydrate = 13, Fat = 0, Calorie = 57, Description = "Cherry is a fruit belonging to the Prunus genus and is generally part of the cherry family. It comes in sweet and sour varieties. Cherries are small-sized, bright red in color, juicy, and have a tart taste.", FoodPicture = "../../../images/foodimages/vişne.jfif", Amount = 100 },

            new Food { FoodID = 92, FoodName = "Lentil soup", FoodCategoryID = 8, Protein = 7.3, Carbonhydrate = 24.8, Fat = 0.5, Calorie = 136, Description = "Lentil soup is a soup whose main ingredient is lentils; it can be vegetarian or contain meat and use brown, red, yellow, green or black lentils, with or without shells. The yellow and red lentils, which have been dehulled, will be crushed as they cook, making a thick soup.", FoodPicture = "../../../images/foodimages/LentilSoup.jfif", Amount = 100 },
            new Food { FoodID = 93, FoodName = "Tomato soup", FoodCategoryID = 8, Protein = 2.3, Carbonhydrate = 9.14, Fat = 2.3, Calorie = 66.36, Description = "Tomato soup is a soup whose main ingredient is tomato. It can be served hot or cold and can be made in a variety of ways. Its texture can be smooth and there are also recipes that include tomato chunks, cream, chicken or vegetable stock, noodles, other vegetable chunks, and meatballs.", FoodPicture = "../../../images/foodimages/Tomatosoup.jfif", Amount = 100 },
            new Food { FoodID = 94, FoodName = "Mushroom soup", FoodCategoryID = 8, Protein = 2.1, Carbonhydrate = 5.1, Fat = 4, Calorie = 76, Description = "Cream of mushroom soup is a simple type of soup in which a basic roux is thinned with cream or milk and then mushrooms and/or mushroom broth is added. It is known as a common type of condensed canned soup in North America..", FoodPicture = "../../../images/foodimages/MushroomSoup.jfif", Amount = 100 },
            new Food { FoodID = 95, FoodName = "Spring soup", FoodCategoryID = 8, Protein = 3.6, Carbonhydrate = 16, Fat = 4, Calorie = 115, Description = "Highland soup or yoghurt soup is a soup whose most important ingredient is yoghurt. It is prepared and consumed in every region of Turkey.", FoodPicture = "../../../images/foodimages/SpringSoup.jfif", Amount = 250 },

            new Food { FoodID = 96, FoodName = "Types of Food", FoodCategoryID = 9, Protein = 3.8, Carbonhydrate = 13.9, Fat = 7.7, Calorie = 192, Description = "Various vegetables combine in a single dish, turning into one of the most satisfying recipes. It is flavored with potatoes, eggplant, zucchini, green peppers, tomatoes and spices.", FoodPicture = "../../../images/foodimages/TypesofFood.jfif", Amount = 250 },
            new Food { FoodID = 97, FoodName = "Dry bean Meal", FoodCategoryID = 9, Protein = 17.5, Carbonhydrate = 45.1, Fat = 0.63, Calorie = 250, Description = "Dry beans are a cooked bean dish in Turkish cuisine. It is made with white beans and olive oil and mostly uses onion and tomato paste. Preferably vegetables or meat can be added to the dish. Dried beans are served with rice pilaf or bulgur pilaf. It can be consumed by adding bread to its water.", FoodPicture = "../../../images/foodimages/DryBeanmeal.jfif", Amount = 250 },
            new Food { FoodID = 98, FoodName = "Chicken Doner", FoodCategoryID = 9, Protein = 20.6, Carbonhydrate = 45.1, Fat = 19.6, Calorie = 148.8, Description = "Chicken doner kebab is made from chicken meat. Chicken doner, which finds its place in Turkish cuisine, is one of the most frequently consumed fast-food products in Turkey.", FoodPicture = "../../../images/foodimages/ChickenDoner.jfif", Amount = 120 },
            new Food { FoodID = 99, FoodName = "Meat Doner", FoodCategoryID = 9, Protein = 29.6, Carbonhydrate = 19.6, Fat = 46.5, Calorie = 301, Description = "Döner or doner kebab is a dish unique to Turkish cuisine, in which pieces of meat seasoned with tallow and local spices are cooked on a skewer and hung upright in front of a wood fire.", FoodPicture = "../../../images/foodimages/MeatDoner.jfif", Amount = 250 },
            new Food { FoodID = 100, FoodName = "Karniyarık Meal", FoodCategoryID = 9, Protein = 11.1, Carbonhydrate = 8.7, Fat = 12.2, Calorie = 191, Description = "Karnıyarık is one of the main eggplant dishes of Turkish cuisine. In addition to eggplant, which is the main ingredient, onions, peppers, tomatoes and minced meat are also used during preparation. A similar eggplant dish is imambayildi. The difference of Imambayildi from Karnıyarık is that there is no meat in it and it is served cold.", FoodPicture = "../../../images/foodimages/KarniyarıkMeal.jfif", Amount = 250 },
            new Food { FoodID = 101, FoodName = "Hamburger", FoodCategoryID = 9, Protein = 13.3, Carbonhydrate = 37.7, Fat = 11.2, Calorie = 312, Description = "Hamburger, or simply Burger, is a type of sandwich made with a meatball, American cheese, and lettuce placed between two slices of round sandwich bread. It is usually served with the addition of different ingredients such as ketchup, mayonnaise, pickles, onions, tomatoes, mustard and so on.", FoodPicture = "../../../images/foodimages/Hamburger.jfif", Amount = 250 },
            new Food { FoodID = 102, FoodName = "Chicken Saute", FoodCategoryID = 9, Protein = 42, Carbonhydrate = 11, Fat = 22, Calorie = 423, Description = "Cooking meat and vegetables in a pan at high heat is called saute. Sauteing, which is a cooking method, is prepared by cooking meat and vegetables in a short time by stirring constantly. It is very important that the materials to be used while sautéing are chopped into small pieces in the form of cubes.", FoodPicture = "../../../images/foodimages/ChickenSaute.jfif", Amount = 240 },
            new Food { FoodID = 103, FoodName = "Boiled Veal", FoodCategoryID = 9, Protein = 12, Carbonhydrate = 1.7, Fat = 3.5, Calorie = 88, Description = "Nutritional values such as the taste of the dish made from beef are also important for the human body.", FoodPicture = "../../../images/foodimages/BoiledVeal.jfif", Amount = 100 },
            new Food { FoodID = 104, FoodName = "Kidney Beans Meal", FoodCategoryID = 9, Protein = 11.5, Carbonhydrate = 30.8, Fat = 10.1, Calorie = 257, Description = "Kidney beans provide many health benefits. It has benefits such as regulating digestion, lowering blood pressure, increasing muscle mass in the body, and reducing the risk of diabetes. It also contributes to mental health by strengthening the bones.", FoodPicture = "../../../images/foodimages/KidneyBeansMeal.jfif", Amount = 100 },

            new Food { FoodID = 105, FoodName = "Pasta", FoodCategoryID = 10, Protein = 5.8, Carbonhydrate = 30.5, Fat = 0.3, Calorie = 157, Description = "Pasta is also very rich in vitamins A, B1, B2, iron, calcium, phosphorus, potassium and protein. It is oil free. It has a cholesterol-lowering effect as it contains very little (1-1,5%) minor fat components and a high rate of linoleic fatty acid.Complex carbohydrates in pasta keep you full because they mix slowly into the blood.", FoodPicture = "../../../images/foodimages/Pasta.jfif", Amount = 100 },
            new Food { FoodID = 106, FoodName = "Bulgur Rice", FoodCategoryID = 10, Protein = 2.7, Carbonhydrate = 18.1, Fat = 3.3, Calorie = 114, Description = "Bulgur, which contains vitamin B1, magnesium and folate, plays an important role for the nervous system and digestive system. Because bulgur contains high levels of minerals and vitamins, it ensures regular and healthy functioning of the intestines. Bulgur, which prevents constipation, also relaxes the mind and provides high energy.", FoodPicture = "../../../images/foodimages/BulgurRice.jfif", Amount = 100 },
            new Food { FoodID = 107, FoodName = "Rice", FoodCategoryID = 10, Protein = 2, Carbonhydrate = 24.7, Fat = 5.8, Calorie = 162, Description = "All rice varieties are a great source of minerals such as calcium and iron; It is also rich in vitamins such as niacin, vitamin D, thiamine, fiber and riboflavin. Rice is easy to digest and has less saturated fat and good cholesterol compared to other foods. Therefore, it is good for heart health.", FoodPicture = "../../../images/foodimages/Rice.jfif", Amount = 100 },

            new Food { FoodID = 108, FoodName = "Seasonal Salad", FoodCategoryID = 11, Protein = 1.3, Carbonhydrate = 3.8, Fat = 1, Calorie = 31, Description = "Although each type of leafy vegetable has different health benefits, they are all low-calorie and high-fiber foods. This means you will fill your stomach with fewer calories. Eating foods that contain fiber can also improve the health of the digestive system. Black lettuce, kale and spinach are rich in vitamins A, C, E and K. Arugula and mustard vegetables also provide most of the B vitamins.", FoodPicture = "../../../images/foodimages/SeasonalSalad.jfif", Amount = 100 },
            new Food { FoodID = 109, FoodName = "Vegetarian Salad", FoodCategoryID = 11, Protein = 2.8, Carbonhydrate = 15.8, Fat = 5.4, Calorie = 124, Description = "According to research, properly planned vegetarian diets are considered healthy. Additionally, it is nutritionally adequate and may provide health benefits in the prevention and treatment of certain diseases.", FoodPicture = "../../../images/foodimages/VegetarianSalad.jfif", Amount = 100 },
            new Food { FoodID = 110, FoodName = "Tuna Salad", FoodCategoryID = 11, Protein = 5.8, Carbonhydrate = 5, Fat = 8.1, Calorie = 117, Description = "Thanks to the Omega 3 fatty acids in it, it controls the cholesterol and balances the heart rhythm. Consumption of tuna salad containing 100 to 300 grams of tuna daily meets the amount of Omega-3 we need and contributes to the strengthening of immunity. Omega 3 is also a skin friend.", FoodPicture = "../../../images/foodimages/TunaSalad.jfif", Amount = 100 },
            new Food { FoodID = 111, FoodName = "Chicken Salad", FoodCategoryID = 11, Protein = 9.7, Carbonhydrate = 3.2, Fat = 1.3, Calorie = 65, Description = "Chicken shepherd's salad is one of the most preferred salad varieties of dieters. Especially the grilled salad with the lean part of the fish helps to keep you full for longer than other salads. It can be preferred as both a light and nutritious meal.", FoodPicture = "../../../images/foodimages/ChickenSalad.jfif", Amount = 100 },

            new Food { FoodID = 112, FoodName = "Rice Pudding", FoodCategoryID = 12, Protein = 1.7, Carbonhydrate = 21.5, Fat = 1.3, Calorie = 105, Description = "Of course, rice pudding is a dessert that conquers hearts not only with its historical features, but also with its benefits to human health. Studies show that the B vitamins in milk are extremely beneficial for the health of the stomach and brain, especially for reasons such as the benefit of being alkaline, the effect of sugar on happiness.", FoodPicture = "../../../images/foodimages/RicePudding.jfif", Amount = 100 },
            new Food { FoodID = 113, FoodName = "Sugar Pare", FoodCategoryID = 12, Protein = 2.6, Carbonhydrate = 45.9, Fat = 8.9, Calorie = 272, Description = "Şekerpare is a sherbet and pasty dessert from Turkish cuisine. It takes place in Ottoman cuisine. After the dough is prepared, before putting the Şekerpare, which is divided into small pieces and separated in a round shape, into the oven, unsalted hazelnuts, peanuts, almonds, walnuts, etc. one each of the dried nuts is placed.", FoodPicture = "../../../images/foodimages/SugarPare.jfif", Amount = 100 },
            new Food { FoodID = 114, FoodName = "San Sebastian Dessert", FoodCategoryID = 12, Protein = 5.2, Carbonhydrate = 24.7, Fat = 22.2, Calorie = 319, Description = "Also known as San Sebastian Cheesecake(Basque Cheesecake)(La Vina San Sebastian Burnt Cheesecake). This Baked Cheesecake recipe was first made in the 1990s at a small patisserie called La Vina located at 31 de Agosto Street in the old quarter of the city of San Sebastián.", FoodPicture = "../../../images/foodimages/SanSebastianDessert.jfif", Amount = 100 },
            new Food { FoodID = 115, FoodName = "Baklava Dessert", FoodCategoryID = 12, Protein = 7.7, Carbonhydrate = 49.3, Fat = 21.4, Calorie = 412, Description = "Baklava is an important dumpling that has a place in Turkish, Middle Eastern, Balkan and South Asian cuisines. It is made by placing walnuts, pistachios, almonds or hazelnuts, depending on the region, between thin phyllo dough. It is generally sweetened with sugar syrup. Honey syrup can also be used.", FoodPicture = "../../../images/foodimages/BaklavaDessert.jfif", Amount = 100 }
           );
        }
    }
}
